### PR TITLE
mistake corrected

### PR DESCRIPTION
**Pull request by Dave0000002**
idk what else to do

### CODE REVIEW

**Comment by Kvngston** [comment]
Please seperate these files na

**Comment by Kvngston** [comment]
And most are still wrong

**Comment by Kvngston** [comment]
Please check the format please this is the third time

**Comment by Kvngston** [comment]
Please check the format please this is the third time

**Comment by Dave0000002** [comment]
Idk how to do it

**Comment by Kvngston** [comment]
Delete all the scripts and add them one by one, the failing ones are
dragging the correct ones down

**Pull request closed without merging**
