### PR TITLE
Chiemerie

### PR DESCRIPTION
**Pull request by ChiemerieBenedict13**
@papa28x4 please merge my file.

### CODE REVIEW

**Comment by ChiemerieBenedict13** [comment]
Please which space? Is I before the + sign.

**Comment by ChiemerieBenedict13** [comment]
Please how?

**Comment by Kvngston** [comment]
The space after + email + " " 

Remove the + " "

**Comment by ChiemerieBenedict13** [comment]
I should remove the second plus sign and the quoted mark sign.
" + email +" " (Before)
" + email "  (After)

**Comment by Kvngston** [comment]
Yes, the way the code is written it parses your email through a regex so
that space might make it to fail

**Comment by ChiemerieBenedict13** [comment]
If I remove the space it will affect it.see this

**Comment by ChiemerieBenedict13** [comment]
If I remove the space it will affect it. Please check this

**Comment by Kvngston** [comment]
It's simple string concatenation look for a way to to remove that space
else your script will keep failing

**Pull request merged**
